import { Metadata } from "next";

export const metadata: Metadata = {
    title: {
        absolute: "",
        default: "Fallback default title",
        template: ""
    },
    description: "Generated by Next.js"
}


function AboutPage() {
    return (
        <h1>About Page</h1>
    );
}

export default AboutPage;